name: miyolla
description: All-in-one tool for Huami wearables
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: any
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/zepp.png
    - images/zepp_life.png
    - images/mi_fitness.png
    - images/notify_lite.png
    - images/notify_for_amazfit.png
    - images/notify_for_mi_band.png
    - images/notify_lite_for_mi_band.png
    - images/master_for_amazfit.png
    - images/master_for_mi_band.png
    - images/tools_and_amazfit.png
    - images/tools_and_mi_band.png
    - images/gadgetbridge.png
    - images/watch_droid_phone.png
    - images/watch_droid_assistant.png
    - images/huafetcher.png
    - images/miyolla.png
  generate: true
