name: miyolla
description: All-in-one tool for Huami wearables
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: any
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/zepp.png
    - images/zepp_life.png
    - images/mi_fitness.png
    - images/notify_lite.png
    - images/notify_for_amazfit.png
    - images/notify_for_mi_band.png
    - images/notify_lite_for_mi_band.png
    - images/master_for_amazfit.png
    - images/master_for_mi_band.png
    - images/tools_and_amazfit.png
    - images/tools_and_mi_band.png
    - images/gadgetbridge.png
    - images/watch_droid_phone.png
    - images/watch_droid_assistant.png
    - images/huafetcher.png
    - images/miyolla.png
    - images/amazfit_ares.png
    - images/amazfit_band_5.png
    - images/amazfit_band_7.png
    - images/amazfit_bip.png
    - images/amazfit_bip_3.png
    - images/amazfit_bip_s.png
    - images/amazfit_bip_u.png
    - images/amazfit_gtr.png
    - images/amazfit_gtr_2.png
    - images/amazfit_gtr_2e.png
    - images/amazfit_gtr_3.png
    - images/amazfit_gtr_42.png
    - images/amazfit_gts.png
    - images/amazfit_gts_2.png
    - images/amazfit_gts_2_mini.png
    - images/amazfit_gts_3.png
    - images/amazfit_gts_4_mini.png
    - images/amazfit_neo.png
    - images/amazfit_smart_scale.png
    - images/amazfit_t_rex.png
    - images/amazfit_t_rex_2.png
    - images/amazfit_t_rex_pro.png
    - images/amazfit_verge_lite.png
    - images/amazfit_x.png
    - images/mi_band_3i.png
    - images/mi_band_4.png
    - images/mi_band_5_nfc.png
    - images/mi_band_6.png
    - images/mi_band_7.png
    - images/zepp_e_circle.png
    - images/zepp_e_square.png
    - images/zepp_z.png
  generate: true
