name: miyolla
description: Firmwares for Huami wearables
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  android_download_manager: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: any
  path_provider: ^2.1.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/core/app/assets/app_icon.png
