name: miyolla
description: All-in-one tool for Huami wearables
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  android_download_manager: ^1.0.3
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.2
  http: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: any
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/zepp.png
    - images/zepp_life.png
    - images/mi_fitness.png
    - images/notify_lite.png
    - images/notify_for_amazfit.png
    - images/notify_for_mi_band.png
    - images/notify_lite_for_mi_band.png
    - images/master_for_amazfit.png
    - images/master_for_mi_band.png
    - images/tools_and_amazfit.png
    - images/tools_and_mi_band.png
    - images/gadgetbridge.png
    - images/watch_droid_phone.png
    - images/watch_droid_assistant.png
    - images/huafetcher.png
    - images/mi_fit.png
    - images/miyolla.png

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "images/miyolla.png"
    icon_size: 256